apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-vhost-config
data:
  "training-dev.whoami.io.conf": |
    server {
      listen 80;
      server_name training-dev.whoami.io;
      gzip "on";
      proxy_cache false;
      server_tokens off;
      add_header X-Frame-Options "SAMEORIGIN";
      location / {
        proxy_pass http://localhost;
        add_header X-Frame-Options: DENY;
      }
    }
